apiVersion: ENC[AES256_GCM,data:vHc=,iv:tlPrkentIH9oO6grpgW7NJtMEY8clwa/4FcWdICwz3E=,tag:Wguy3IuXdyrOEQx8HaL93Q==,type:str]
kind: ENC[AES256_GCM,data:ubB8a4yS,iv:yoxB1V6xohCbGz1XWjoB2jYhx53GAri+Yi96HyplzjY=,tag:5s6JFQVnSHrumbLibIFbzA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:w/d69dNx8QKZ2nBJ/JU=,iv:WWORgASYVZ4i00eJZYqz8Ooep03RGUESW5ewzu6n6ZU=,tag:Y6qfVVglI4wQspouOV/6DQ==,type:str]
    namespace: ENC[AES256_GCM,data:wq1VnVTb433pfb6Yz4GpAA==,iv:2uPcDueIrO6oTJwGkHb6E3uf5gg/wNBEL/kj0lgIWGs=,tag:LP5hDCrUuPlBLN7tk2OOOw==,type:str]
type: ENC[AES256_GCM,data:hic4m996,iv:8iL4+fE0Azq2eiExmL09rPZSpdw4HWlKjwvizvyIg8w=,tag:BSXEcON7b7qXHZsRqBUOZw==,type:str]
stringData:
    kheops_authdb_pass: ENC[AES256_GCM,data:kXvCV5O4qY8pUsg76tNfURIAMMgs4VxB1aFYf7/Mujn/cTpLhg9ICcs=,iv:n3kEzT1OyafR1ENlwyhAOCb+5n3xVZqZPQpyoyC21pU=,tag:w2myHdODC0yzlTw23z/Djw==,type:str]
    kheops_pacsdb_pass: ENC[AES256_GCM,data:0pki119E/3odf2a3x1pO2Tu6yDgtiw9vsJRiYNkwkD/lbPbCMjrxRdc=,iv:vmktFzkRBlJOcMyn4vmQe+fiHJagzCBtN3/dKegKnXo=,tag:Tni+KaVTT8IDpdAJ+/yvQA==,type:str]
    kheops_auth_hmasecret: ENC[AES256_GCM,data:z3M8MfCXUm/AuSYUYtW4CfmU80bYp9MgZDkLx1z66IFgvtPE1pm6JRJpOhka,iv:s7ZOFL+G4d4rbw5IqjP6VKLgblz+OM77gaUzAC+2w04=,tag:MFgPt6l+OC720D7SyU13zQ==,type:str]
    kheops_auth_hmasecret_post: ENC[AES256_GCM,data:1004I7tl2yoRid2Zc75A2gkNXbzWXOUPS/py5UdlRrZfmXUTZE8qjax3rpGQ,iv:D21RLuMFNmQ0OR5w2GOp2I2oBgWuAgDwx2G/t1ETIWI=,tag:KLIGU1AH+95GYwT9f9MvRA==,type:str]
    kheops_client_dicomwebproxysecret: ENC[AES256_GCM,data:mo6xwcaJ6PKo5IfeS73mfKfBeG0WELxXRm0tTawWU8V4YY3g1cGxEPDvhhTz,iv:4GsvDtE3qe0+q1+XDXkQbIUUOAd7tiM2ZaaAfbLKMpo=,tag:ZEoYRZdyuAHE4MrzUW1Twg==,type:str]
    kheops_client_zippersecret: ENC[AES256_GCM,data:V1y/D9X7nXcc1odx4vLZPBu2bY1BUB4axijMx48e6AIzgpMbqN3u+1zu3ZY=,iv:6WFHMHzHIQPNCTaq8aAY1+xzO7rgm5Se88HHp/pyQxA=,tag:oQa2nbOfxgDYOW9FQP+RmQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-07T11:46:15Z"
    mac: ENC[AES256_GCM,data:13RAPqPAmoHaFY24B6PyU7Nazk0mjFB21NrK/WOGuNPJWusntMJTvImYSx/qiuPus1t273ifrqv+Cs8EhGT4c6bXJFjjZF0icEzgfGNIZtR3DAa2uEGFv8geG6a3sPLFprdz5ZACCYdVbaY1QnEsIBGKoS7yAUbs1igIX1PCzTo=,iv:Ds7LPoNF3lVd0Bu+ZKb73DHLdfNZSvCPFHClkU88rOs=,tag:9nz3Sq1u65xFIzNPTAgGpg==,type:str]
    pgp:
        - created_at: "2022-07-07T11:46:14Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAyRDiksqh3g9AQ//VIJsy/D+aUiQET+XRfDIwIhtnlSICcEO2qRDWCgKsNP4
            VyoZYX4sMgwSKVrH9LLdzRnFsY/d325KnTR/1mclqfVbtiMnjlCoJ7fkNXEIf7dE
            lH0uf4Xr260RZTtHVhkGSHVAy/mkeAyEc93bsEDU9THl0uk7mrOrfAJJrTjqJUK4
            QGMwd5Cj+UZGj3fQGQgYdOyHnaAcmZskh4Q3AZF7DLe8lWjuNk+Whb737Kod5zFY
            /BEQeP+T1M3XdJWHbKLXRLPgCjYW+HXYQNBmfJow48TncUb1sq06KEaiuArYLgi/
            Lj+q6/08WQ/B00UwCigK0aGMjF6L9qSn+dmoyZS/AvXo0hdwVMXmNe1FqRIsUjaH
            BH2Ehzi38F2NZkn2qEyhLBb8vlm4Guic7U5frjRvI63tnK2siH1PS5sSbMm3PTAd
            lQ8UiMpGh3R2OTw064/msGsxRpJbd0gTPf+D4k9v5Q/geL5kJLZ+s2TUrqdUVs6u
            THUs6ldZJhLyXag0HssPzhEs27+z09ksACCz5Ipm8e9iSXLTutyeBpje40KP495G
            ywC1sqPrCIGp9dJKax8WOaad5y709Gc62JH7vnBaG5glMiVMtcnacW4EP2W9YIRk
            AfJ+XfzTQum9GbPE2TFOgddhGKk81tVyThcWZKK2L6uTp+tx+WIs+HOFL05AR/DS
            XgGYDV9/eOtnCa8O7vUb41/aFhXNydwnigLJiJCk/qkO2BYosglPVHrtMcOXIkot
            DSR7hIJz7ARUxxWXq0atr6OTnHxayX+/O07i5f0ifdIOnvMwht+Ndo4VELO1ZZw=
            =PzH9
            -----END PGP MESSAGE-----
          fp: C15BAA8125B809495661DDFC6659A638EFB83602
    unencrypted_suffix: _unencrypted
    version: 3.7.3
