apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
        k8s-app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:17.0.0
          args: ["start-dev"]
          env:
            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "admin"
            - name: KC_PROXY
              value: "edge"
            - name: KEYCLOAK_IMPORT
              value: "/tmp/kheops-realm.json"
            - name: KEYCLOAK_FRONTEND_URL
              value: "http://127.0.0.1:8080/auth"
          ports:
          - containerPort: 8080
          volumeMounts:
            - name: keycloakrealmdata
              mountPath: /tmp/kheops-realm.json
              subPath: kheops-realm.json
          readinessProbe:
            httpGet:
              path: /realms/master
              port: 8080
      volumes:
        - name: keycloakrealmdata
          configMap:
            name: keycloak-config