apiVersion: apps/v1
kind: Deployment
metadata:
  name: kheopsreverseproxy
spec:
  selector:
    matchLabels:
      app: kheopsreverseproxy
  replicas: 1
  template:
    metadata:
      labels:
        app: kheopsreverseproxy
    spec:
      containers:
      - name: kheopsreverseproxy
        image: osirixfoundation/kheops-reverse-proxy:v1.0.8-insecure
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: kheops-config
        - configMapRef:
            name: kheops-config-common
