apiVersion: apps/v1
kind: Deployment
metadata:
  name: ohif
  namespace: postgres-operator
  labels:
    app: ohif
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ohif
  template:
    metadata:
      labels:
        app: ohif
        k8s-app: ohif
    spec:
      containers:
        - name: ohif
          image: osirixfoundation/viewer:v4.12.6
          ports:
          - containerPort: 80
          readinessProbe:
            httpGet:
              path: /viewer/1.3.6.1.4.1.14519.5.2.1.7009.2403.871108593056125491804754960339
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 10