apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-kheops
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: kheops.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kheopsreverseproxy
                port:
                  number: 80
  ingressClassName: nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-keycloak
spec:
  rules:
    - host: keycloak.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8080
  ingressClassName: nginx