apiVersion: v1
kind: Secret
metadata:
  name: pacs-importer.secrets
type: Opaque
stringData:
  pacs_importer_token: >
    ***Token to use***
---
apiVersion: batch/v1
kind: Job
metadata:
  name: pacs-importer
spec:
  template:
    spec:
      containers:
      - name: pacs-importer
        image: osirixfoundation/kheops-pacs-importer:v0.9.1-google-branch
        envFrom:
        - configMapRef:
            name: kheops-config
        - configMapRef:
            name: kheops-config-common
        volumeMounts:
        - name: secrets
          mountPath: "/run/secrets/privkey.pem"
          subPath: privkey.pem
        - name: pacs-importer-secrets
          mountPath: "/run/secrets/importer_token"
          subPath: importer_token
      restartPolicy: Never
      volumes:
      - name: secrets
        secret:
          secretName: kheops.secrets
          items:
          - key: cloudhealth_service_account_private_key
            path: privkey.pem
      - name: pacs-importer-secrets
        secret:
          secretName: pacs-importer.secrets
          items:
          - key: pacs_importer_token
            path: importer_token
