apiVersion: v1
kind: Service
metadata:
  name: kheopsreverseproxy
  namespace: kheops-alzheimer
  labels:
    app: kheopsreverseproxy
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8042
  selector:
    app: kheopsreverseproxy

