apiVersion: v1
kind: Service
metadata:
  name: kheopsdicomwebproxy
  namespace: kheops-alzheimer
  labels:
    app: kheopsdicomwebproxy
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: kheopsdicomwebproxy
