---
version: "3.1"
services:
  keycloak:
    image: jboss/keycloak:8.0.1
    container_name: keycloak
    command: ["-b", "0.0.0.0", "-Dkeycloak.migration.strategy=IGNORE_EXISTING"]
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD_FILE: /run/secrets/keycloak_admin_password
      KEYCLOAK_IMPORT: /tmp/kheops-realm.json
    volumes:
      - keycloak-standalone-data:/opt/jboss/keycloak/standalone/data
      - ./realm/kheops-realm.json:/tmp/kheops-realm.json:cached
      - ./themes/kheops:/opt/jboss/keycloak/themes/kheops:cached
    secrets:
      - keycloak_admin_password
    networks:
      - keycloak_network

  ldap:
    container_name: ldap
    image: dcm4che/slapd-dcm4chee:2.4.48-21.0
    env_file: docker-compose.env
    networks:
      - pacs_network

  pacs-postgres:
    container_name: pacspostgres
    image: dcm4che/postgres-dcm4chee:12.1-21
    logging:
      driver: json-file
      options:
        max-size: "10m"
    environment:
      POSTGRES_DB: kheops_pacs
      POSTGRES_USER: kheops_pacs
      POSTGRES_PASSWORD_FILE: /run/secrets/kheops_pacsdb_pass
    env_file: docker-compose.env
    volumes:
      - dcm4chee-db-data:/var/lib/postgresql/data
    secrets:
      - kheops_pacsdb_pass
    networks:
      - pacs_network

  pacs-arc:
    container_name: pacsarc
    image: dcm4che/dcm4chee-arc-psql:5.21.0
    env_file: docker-compose.env
    environment:
      POSTGRES_DB: kheops_pacs
      POSTGRES_USER: kheops_pacs
      POSTGRES_PASSWORD_FILE: /run/secrets/kheops_pacsdb_pass
      WILDFLY_CHOWN: /storage /opt/wildfly/standalone
      WILDFLY_WAIT_FOR: ldap:389 pacspostgres:5432
      JAVA_OPTS: -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -agentlib:jdwp=transport=dt_socket,address=8787,server=y,suspend=n
    secrets:
      - kheops_pacsdb_pass
    depends_on:
      - ldap
      - pacs-postgres
    volumes:
      - dcm4chee-arc-wildfly:/opt/wildfly/standalone
      - dcm4chee-arc-storage:/storage
    networks:
      - pacs_network

  kheops-postgres:
    container_name: kheopspostgres
    image: postgres:12.1-alpine
    volumes:
      - kheops-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: kheops
      POSTGRES_USER: kheopsuser
      POSTGRES_PASSWORD_FILE: /run/secrets/kheops_authdb_pass
    secrets:
      - kheops_authdb_pass
    networks:
      - kheops_network

  kheops-authorization:
    container_name: kheopsauthorization
    image: osirixfoundation/kheops-authorization:v0.9.2-noissuer
    env_file: docker-compose.env
    environment:
      CATALINA_OPTS: -Duser.timezone=UTC
      KHEOPS_KEYCLOAK_URI: http://keycloak:8080
    depends_on:
      - kheops-postgres
    secrets:
      - kheops_auth_hmasecret
      - kheops_authdb_pass
      - kheops_keycloak_clientsecret
      - kheops_client_dicomwebproxysecret
      - kheops_client_zippersecret
      - kheops_metric_ressource_password
    networks:
      - kheops_network
      - keycloak_network

  kheops-zipper:
    container_name: kheopszipper
    image: osirixfoundation/kheops-zipper:v0.9.2
    env_file: docker-compose.env
    secrets:
      - kheops_client_zippersecret
    networks:
      - kheops_network

  kheops-ui:
    container_name: kheopsui
    image: osirixfoundation/kheops-ui:v0.9.2
    environment:
      KHEOPS_KEYCLOAK_URI: http://127.0.0.1:8080
    env_file: docker-compose.env
    networks:
      - frontend_network

  kheops-dicomweb-proxy:
    container_name: kheopsdicomwebproxy
    image: osirixfoundation/kheops-dicomweb-proxy:v0.9.2
    env_file: docker-compose.env
    secrets:
      - kheops_auth_hmasecret_post
      - kheops_client_dicomwebproxysecret
    networks:
      - kheops_network

  kheops-reverse-proxy:
    image: osirixfoundation/kheops-reverse-proxy:v0.9.2-insecure
    container_name: kheopsreverseproxy
    env_file: docker-compose.env
    ports:
      - "80:8042"
    depends_on:
      - kheops-authorization
      - kheops-dicomweb-proxy
      - kheops-ui
      - kheops-zipper
    networks:
      - kheops_network
      - frontend_network

  pacs-authorization-proxy:
    container_name: pacsauthorizationproxy
    env_file: docker-compose.env
    image: osirixfoundation/pacs-authorization-proxy:v0.9.2
    depends_on:
      - pacs-arc
    secrets:
      - kheops_auth_hmasecret
      - kheops_auth_hmasecret_post
    networks:
      - pacs_network
      - kheops_network

secrets:
  keycloak_admin_password:
    file: secrets/keycloak_admin_password
  kheops_authdb_pass:
    file: secrets/kheops_authdb_pass
  kheops_pacsdb_pass:
    file: secrets/kheops_pacsdb_pass
  kheops_auth_hmasecret:
    file: secrets/kheops_auth_hmasecret
  kheops_auth_hmasecret_post:
    file: secrets/kheops_auth_hmasecret_post
  kheops_keycloak_clientsecret:
    file: secrets/kheops_keycloak_clientsecret
  kheops_client_dicomwebproxysecret:
    file: secrets/kheops_client_dicomwebproxysecret
  kheops_client_zippersecret:
    file: secrets/kheops_client_zippersecret
  kheops_metric_ressource_password:
    file: secrets/kheops_metric_ressource_password

volumes:
  keycloak-standalone-data:
  dcm4chee-db-data:
  dcm4chee-arc-wildfly:
  dcm4chee-arc-storage:
  kheops-db-data:

networks:
  kheops_network:
    driver: bridge
  pacs_network:
    driver: bridge
  frontend_network:
    driver: bridge
  keycloak_network:
    driver: bridge
