apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: postgres-operator
  labels:
    app: keycloak
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: keycloak