apiVersion: v1
kind: Service
metadata:
  name: kheopsreverseproxy
  labels:
    app: kheopsreverseproxy
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: kheopsreverseproxy
