apiVersion: v1
kind: Service
metadata:
  name: kheopszipper
  namespace: postgres-operator
  labels:
    app: kheopszipper
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: kheopszipper
