apiVersion: v1
kind: Service
metadata:
  name: ohif
  namespace: kheops-utils
  labels:
    app: ohif
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: ohif