apiVersion: batch/v1
kind: Job
metadata:
  name: pacs-importer
spec:
  template:
    spec:
      containers:
      - name: pacs-importer
        image: osirixfoundation/kheops-pacs-importer:v0.9.1-google-branch
        imagePullPolicy: Always
        env:
        - name: IMPORTER_TOKEN
          value: "mvt4iqOe3fQHhVxfaFyOlX"
        envFrom:
        - configMapRef:
            name: kheops-config
        - configMapRef:
            name: kheops-config-common
        volumeMounts:
        - name: secrets
          mountPath: "/run/secrets/privkey.pem"
          subPath: privkey.pem
      restartPolicy: Never
      volumes:
        - name: secrets
          secret:
            secretName: kheops.secrets
            items:
            - key: cloudhealth_service_account_private_key
              path: privkey.pem
      restartPolicy: Never
  backoffLimit: 4
