apiVersion: v1
kind: Service
metadata:
  name: kheopsauthorization
  namespace: kheops-aneux
  labels:
    app: kheopsauthorization
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: kheopsauthorization
