apiVersion: v1
kind: Service
metadata:
  name: pacsauthorizationproxy
  namespace: kheops-aneux
  labels:
    app: pacsauthorizationproxy
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: pacsauthorizationproxy
