version: '3'

services:
  portainer:
    image: portainer/portainer
    container_name: my_portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - "9000:9000"

volumes:
  portainer_data:
