version: "3"
services:

  ldap:
    image: dcm4che/slapd-dcm4chee:2.4.44-13.0
    ports:
      - "389:389"
    env_file: docker-compose.env
    volumes:
      - /var/local/dcm4chee-arc/ldap:/var/lib/ldap
      - /var/local/dcm4chee-arc/slapd.d:/etc/ldap/slapd.d
  db:
    image: dcm4che/postgres-dcm4chee:10.0-13
    ports:
      - "5432:5432"
    env_file: docker-compose.env
    volumes:
      - /var/local/dcm4chee-arc/db:/var/lib/postgresql/data
  arc:
    image: dcm4che/dcm4chee-arc-psql:5.13.0
    ports:
      - "8080:8080"
      - "8443:8443"
      - "9990:9990"
      - "8787:8787"
      - "11112:11112"
      - "2575:2575"
    env_file: docker-compose.env
    environment:
      WILDFLY_CHOWN: /opt/wildfly/standalone /storage
      WILDFLY_WAIT_FOR: ldap:389 db:5432
      JAVA_OPTS: -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -agentlib:jdwp=transport=dt_socket,address=8787,server=y,suspend=n
    depends_on:
      - ldap
      - db
    volumes:
      - /var/local/dcm4chee-arc/wildfly:/opt/wildfly/standalone
      - /var/local/dcm4chee-arc/storage:/storage


  kheops-mysql:
    container_name: kheopsmysql
    image: kheopsmysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mypwd
    volumes:
      - kheops-mysql-volume:/var/lib/mysql


  tomcta-authorization:
    container_name: tomcataut
    image: tomcataut

volumes:
  kheops-mysql-volume:
