apiVersion: apps/v1
kind: Deployment
metadata:
  name: kheopsui
  namespace: kheops-lavim
spec:
  selector:
    matchLabels:
      app: kheopsui
  replicas: 1
  template:
    metadata:
      labels:
        app: kheopsui
    spec:
      containers:
      - name: kheopsui
        image: osirixfoundation/kheops-ui:v1.1
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: kheops-config