apiVersion: apps/v1
kind: Deployment
metadata:
  name: kheopsdicomwebproxy
  namespace: kheops-lavim
spec:
  selector:
    matchLabels:
      app: kheopsdicomwebproxy
  replicas: 1
  template:
    metadata:
      labels:
        app: kheopsdicomwebproxy
    spec:
      containers:
      - name: kheopsdicomwebproxy
        image: osirixfoundation/kheops-dicomweb-proxy:nikpap_unige_k8s
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: kheops-lavim-config
        volumeMounts:
        - name: secrets
          mountPath: "/run/secrets/kheops_auth_hmasecret_post"
          subPath: kheops_auth_hmasecret_post
        - name: secrets
          mountPath: "/run/secrets/kheops_client_dicomwebproxysecret"
          subPath: kheops_client_dicomwebproxysecret
      volumes:
      - name: secrets
        secret:
          secretName: kheops-lavim.secrets
          items:
          - key: kheops_auth_hmasecret_post
            path: kheops_auth_hmasecret_post
          - key: kheops_client_dicomwebproxysecret
            path: kheops_client_dicomwebproxysecret
