apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldap
  namespace: kheops-lavim
spec:
  selector:
    matchLabels:
      app: ldap
  replicas: 1
  template:
    metadata:
      labels:
        app: ldap
    spec:
      containers:
        - name: ldap
          image: dcm4che/slapd-dcm4chee:2.6.0-25.1
          ports:
            - containerPort: 389
          envFrom:
            - configMapRef:
                name: kheops-lavim-config