apiVersion: v1
kind: Secret
metadata:
  name: kheops.secrets
type: Opaque
stringData:
  kheops_authdb_pass: >
  kheops_auth_hmasecret: >
  kheops_auth_hmasecret_post: >
  kheops_client_dicomwebproxysecret: >
  kheops_client_zippersecret: >
  kheops_pacsdb_pass: >
