apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: kheops-utils
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
        k8s-app: keycloak
    spec:
      containers:
        - name: keycloak
          image: jboss/keycloak:16.1.1
          args: ["-b", "0.0.0.0"]
          envFrom:
          - configMapRef:
              name: keycloak-config
          ports:
          - containerPort: 8080
          volumeMounts:
            - name: keycloak-realm-data
              mountPath: /tmp/kheops-realm.json
              subPath: kheops-realm.json
            - name: keycloak
              mountPath: /opt/jboss/keycloak/standalone/data/password-blacklists
#            - name: keycloak-theme-data
#              mountPath: /opt/jboss/keycloak/themes/kheops
          readinessProbe:
            httpGet:
              path: /auth/realms/kheops/
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
      initContainers:
        - name: install
          image: busybox:1.28
          command:
            - wget
            - "-O"
            - "/keycloak/10_million_password_list_top_1000000.txt"
            - https://github.com/OsiriX-Foundation/KheopsOrchestration/raw/kubernetes-unige/utils/keycloak/10_million_password_list_top_1000000.txt
          volumeMounts:
            - name: keycloak
              mountPath: "/keycloak"
      volumes:
        - name: keycloak-realm-data
          configMap:
            name: keycloak-realm-config
        - name: keycloak
          emptyDir: {}
#        - name: keycloak-theme-data
#          hostPath:
#            path: /Users/nikpap/IdeaProjects/KheopsOrchestration/utils/deployments/themes/kheops/